### ISSUE TITLE
Squebi does not load in Chrome

### ISSUE THREAD

**Issue by wikier** [tkurz/squebi#8]
In Chrome 43+, the Squebi query interface never presents as though it's finished loading. Chrome's JavaScript console reports the following error:

```
Uncaught SyntaxError: Unexpected identifier
```

Occasionally, the query box will show after reloading the page.

Issue from Marmotta: https://issues.apache.org/jira/browse/MARMOTTA-614

**Comment by tkurz** [comment]
Should be fixed in version 1.0.3
